## 带有 #[expected_failure(abort_code = 1)] 的测试在什么情况下通过？

A. 当测试函数没有错误
B. 当测试函数以中止代码 1 报错
C. 当测试函数以中止代码 2 报错